name: Test

on: [ push ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.7
          architecture: x64
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -q pipenv codecov
          pipenv install -q pytest-cov
          pipenv sync --dev
      - name: Rodar flake8
        run: |
          pipenv run flake8
      - name: Rodar Testes Automáticos
        run: |
          pipenv run pytest libpythonpro --cov=libpythonpro
      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: 'c6aa616d-2a0f-4884-9e60-e8e110e7835f'
        run: |
          pipenv run codecov