name: Test

on: [ push ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.7
          architecture: x64
      - name: Instalar dependências
        run: |
          pip install -r requirements-dev.txt
      - name: Rodar flake8
        run: |
            flake8
      - name: Rodar Testes Automáticos
        run: |
          pytest --cov=libpythonpro
      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: 'c6aa616d-2a0f-4884-9e60-e8e110e7835f'
        run: |
          codecov